#!/bin/bash

if [ ! -f .env ]; then
   echo "File .env needs to exist."
   exit -1
fi

source .env

if [ ! "$ASTRA_USERNAME" ]; then
    echo "env variable ASTRA_USERNAME needs to be set"
    exit -1
fi

if [ ! "$ASTRA_PASSWORD" ]; then
    echo "env variable ASTRA_PASSWORD needs to be set"
    exit -1
fi

if [ ! -f /workspace/bootcamp-fullstack-apps-with-cassandra/secure-connect-workshops.zip  ]; then
   echo "Secure connect bundle to connect to Astra does not exist."
   exit -1
fi

cat ./java/src/main/java/com/datastax/workshop/DBConnection.java.init | \
    sed "s/\$ASTRA_USERNAME/$ASTRA_USERNAME/" | \
    sed "s/\$ASTRA_PASSWORD/$ASTRA_PASSWORD/" > \
    ./java/src/main/java/com/datastax/workshop/DBConnection.java

cat ./javascript/connection.js.init | \
    sed "s/\$ASTRA_USERNAME/$ASTRA_USERNAME/" | \
    sed "s/\$ASTRA_PASSWORD/$ASTRA_PASSWORD/" > \
    ./javascript/connection.js

cat ./python/connection.py.init | \
    sed "s/\$ASTRA_USERNAME/$ASTRA_USERNAME/" | \
    sed "s/\$ASTRA_PASSWORD/$ASTRA_PASSWORD/" > \
    ./python/connection.py

echo "Astra credentials plugged into all language environments. Please verify!"

cat ~/.zshrc.init > ~/.zshrc && echo "/workspace/bootcamp-fullstack-apps-with-cassandra/cqlsh-astra/bin/cqlsh \\
	--secure-connect-bundle=/workspace/bootcamp-fullstack-apps-with-cassandra/secure-connect-workshops.zip  \\
	-u $ASTRA_USERNAME \\
	-p $ASTRA_PASSWORD" >> ~/.zshrc
